prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    evaluationInterval: 15s
    podMonitorNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: devops
    podMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: true